# Generated by Django 2.0.2 on 2018-05-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.CharField(default='', max_length=150),
        ),
    ]
