# Generated by Django 2.0.2 on 2018-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_schedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
    ]
